# Generated by Django 4.2.1 on 2023-08-18 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trucking_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trucking',
            name='number_plate',
        ),
    ]
