# Generated by Django 4.2.1 on 2023-08-08 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='logistics_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name_of_goods', models.CharField(max_length=255)),
                ('current_location', models.CharField(max_length=50)),
                ('destination', models.CharField(max_length=70)),
                ('nature_of_goods', models.CharField(max_length=100)),
                ('weight_of_goods', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('recipient_name', models.CharField(max_length=30)),
                ('email_address_of_sender', models.EmailField(max_length=254)),
            ],
        ),
    ]
