# Generated by Django 4.2.1 on 2023-08-08 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logistics_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Natureofproducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category1', models.CharField(max_length=30)),
                ('category2', models.CharField(max_length=30)),
                ('category3', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='logistics_details',
            name='nature_of_goods',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistics_app.natureofproducts'),
        ),
    ]
