# Generated by Django 4.2.1 on 2023-08-08 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistics_app', '0002_natureofproducts_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='logistics_details',
            new_name='Logisticsdetails',
        ),
    ]
