# Generated by Django 4.2.1 on 2023-08-08 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistics_app', '0003_rename_logistics_details_logisticsdetails'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logisticsdetails',
            old_name='Name_of_goods',
            new_name='name_of_goods',
        ),
    ]
