# Generated by Django 4.2.1 on 2023-08-08 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logistics_app', '0004_rename_name_of_goods_logisticsdetails_name_of_goods'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logisticsdetails',
            name='nature_of_goods',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='logistics_app.natureofproducts'),
        ),
    ]
