# Generated by Django 4.2.1 on 2023-08-10 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logistics_app', '0005_alter_logisticsdetails_nature_of_goods'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_nature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nature', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='logisticsdetails',
            name='nature_of_goods',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='logistics_app.product_nature'),
        ),
        migrations.DeleteModel(
            name='Natureofproducts',
        ),
    ]
