# Generated by Django 4.2.1 on 2023-08-10 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logistics_app', '0006_product_nature_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logisticsdetails',
            name='nature_of_goods',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistics_app.product_nature'),
        ),
    ]
