# Generated by Django 4.2.1 on 2023-08-17 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255)),
                ('secondname', models.CharField(max_length=255)),
                ('email_address', models.EmailField(max_length=254)),
                ('location', models.CharField(max_length=255)),
                ('payment_mode', models.CharField(choices=[('M', 'M-pesa'), ('P', 'Paypal'), ('O', 'On-delivery')], default='M-pesa', max_length=1)),
                ('amount', models.FloatField()),
            ],
        ),
    ]
