# Generated by Django 4.2.1 on 2023-08-17 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment_app', '0002_cart'),
        ('warehouse_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specifications',
            fields=[
                ('warehouse_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='warehouse_app.warehouse')),
            ],
            bases=('warehouse_app.warehouse',),
        ),
    ]
