# Generated by Django 4.2.1 on 2023-08-28 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment_app', '0003_specifications'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='amount',
        ),
    ]
