# Generated by Django 4.2.1 on 2023-08-28 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_app', '0004_remove_payment_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='country',
            field=models.CharField(choices=[('K', 'Kenya'), ('T', 'Tanzania'), ('U', 'Uganda'), ('B', 'Burundi'), ('R', 'Rwanda'), ('S', 'Sudan')], default='Kenya', max_length=1),
        ),
    ]
