# Generated by Django 4.2.1 on 2023-08-28 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_app', '0005_payment_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='zip',
            field=models.IntegerField(default=100),
        ),
    ]
