# Generated by Django 4.2.1 on 2023-08-31 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment_app', '0006_payment_zip'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Payment',
            new_name='Billing',
        ),
    ]
