# Generated by Django 4.2.1 on 2023-08-31 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_app', '0007_rename_payment_billing'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='address_line',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='billing',
            name='company_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='billing',
            name='phone_number',
            field=models.IntegerField(default=254),
            preserve_default=False,
        ),
    ]
