# Generated by Django 4.2.1 on 2023-08-17 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('logistics_app', '0007_alter_logisticsdetails_nature_of_goods'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_goods', models.CharField(max_length=140)),
                ('name_of_owner', models.CharField(max_length=200)),
                ('weight_of_goods', models.IntegerField()),
                ('location', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=222)),
                ('nature_of_goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistics_app.product_nature')),
            ],
        ),
    ]
